Import required libraries¶



# NumPy Tutorial
NumPy (Numerical Python) is a fundamental Python library for numerical computing. Learning NumPy is important because:

Efficient Computation – It provides fast operations on large datasets using optimized C and Fortran code.

Multi-Dimensional Arrays – NumPy's ndarray is more efficient than Python lists for numerical computations.

Broadcasting & Vectorization – Eliminates the need for loops, making code more concise and efficient.

Integration with AI & ML – Essential for AI, ML, and Deep Learning frameworks like TensorFlow and PyTorch.

Scientific & Data Analysis Applications – Widely used in scientific computing, data analysis, and engineering.

In [2]:
import numpy as np

Exercise 1. Create the array



In [2]:
arr=np.array([23,45,67])
print(arr)

[23 45 67]


Exercise 2. Generating a Range of Numbers






In [3]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


Exercise 3. How to create a boolean array?¶



In [5]:
x=np.full((3,3),False,dtype=bool)
print(x)

[[False False False]
 [False False False]
 [False False False]]


Exercise 4. How to extract items that satisfy a given condition from 1D array?¶



In [8]:
x=np.arange(10)
y=x[x%2==0]
print(y)

[0 2 4 6 8]


Exercise 5. How to replace items that satisfy a condition with another value in numpy array?¶



In [14]:
x=np.arange(10)
x[x%2==0]=-2
x


array([-2,  1, -2,  3, -2,  5, -2,  7, -2,  9])

Exercise 6. How to replace items that satisfy a condition without affecting the original array?¶



In [18]:
arr=np.arange(1,11)
out=arr.copy()
out[out%2==0]=-1
print(out)# modified array
print(arr) #original array


[ 1 -1  3 -1  5 -1  7 -1  9 -1]
[ 1  2  3  4  5  6  7  8  9 10]


Exercise 7. How to reshape an array?¶



In [21]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
y=x.reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
y=x.reshape(2,-1)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Exercise 8. How to stack two arrays vertically?¶



In [ ]:
x=np.arange(10).reshape(2,5)
y=np.arange(10,20).reshape(2,-1)
print(x)



[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
print(y)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
np.vstack([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Exercise 9. How to stack two arrays horizontally?¶



In [ ]:
a=np.array([1,3,6])
b=np.array([2,4,6])
c=np.hstack([a,b])
print(c)

[1 3 6 2 4 6]


array([ 6, 45, 46])

[ 1  3 54 90]


Exercise 10. How to generate custom sequences in numpy without hardcoding?¶



In [9]:
x=np.array([1,2,3])
y=np.repeat(x,3)
print(y)
z=np.tile(x,3)
print(z)
np.hstack([y,z])

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Exercise 11. How to get the common items between two python numpy arrays?¶



In [ ]:
a=np.array([1,3,6,54,46,45,90])
b=np.array([2,4,6,8,0,45,46,99,100])
np.intersect1d(a,b)

Exercise 12. How to remove from one array those items that exist in another?¶



In [ ]:
a=np.array([1,3,6,54,46,45,90])
b=np.array([2,4,6,8,0,45,46,99,100])
c=np.setdiff1d(a,b)
print(c)

Exercise 13. How to get the positions where elements of two arrays match?¶



In [11]:
a=np.array([1,3,6,54,46,45,90])
b=np.array([2,4,6,8,0,45,46])
np.where(a==b)

(array([2, 5]),)

Exercise 14. How to extract all numbers between a given range from a numpy array?¶



In [12]:
a=np.array([1,3,6,54,46,45,90])
a[(a>=5)&(a<=60)]

array([ 6, 54, 46, 45])

Exercise 15. How to make a python function that handles scalars to work on numpy arrays?¶



Exercise 16. How to swap two columns in a 2d numpy array?¶



In [14]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
y=x[:,[1,0,2]]
y

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Exercise 17. How to swap two rows in a 2d numpy array?¶



In [18]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
y=x[[0,2,1],:]
y

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

Exercise 18. How to reverse the rows of a 2D array?¶



In [ ]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
x[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [23]:
x[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Exercise 19. How to reverse the columns of a 2D array?¶



In [24]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
x[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Exercise 20. How to create a 2D array containing random floats between 5 and 10?¶



In [27]:
random_arr=np.random.uniform(5,10,size=(5,3))
random_arr

array([[9.64278059, 5.78314   , 9.55266182],
       [9.85605537, 6.1224376 , 9.388577  ],
       [5.01567644, 9.45859027, 6.25317985],
       [9.63340624, 5.65643538, 8.21939136],
       [7.24616833, 8.04459003, 5.21927059]])

array([[7.157, 9.644, 9.51 ],
       [5.587, 5.474, 9.894],
       [5.116, 8.906, 8.226],
       [5.522, 9.241, 9.309],
       [5.205, 6.84 , 6.225]])

Exercise 21. How to print only 3 decimal places in python numpy array?¶



In [29]:
random_arr=np.random.uniform(5,10,size=(5,3))
np.set_printoptions(precision=3)
random_arr

array([[5.073, 5.264, 7.836],
       [9.089, 7.555, 7.679],
       [9.646, 5.537, 8.625],
       [6.578, 8.592, 7.056],
       [6.469, 5.661, 6.383]])

Exercise 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?¶



In [30]:
random_arr=np.random.uniform(5,10,size=(5,3))
random_arr

array([[5.316, 7.15 , 7.434],
       [8.523, 8.539, 7.017],
       [5.63 , 8.444, 7.032],
       [8.697, 6.703, 7.85 ],
       [5.482, 5.025, 5.386]])

In [ ]:

random_arr/1e10

array([[5.316e-10, 7.150e-10, 7.434e-10],
       [8.523e-10, 8.539e-10, 7.017e-10],
       [5.630e-10, 8.444e-10, 7.032e-10],
       [8.697e-10, 6.703e-10, 7.850e-10],
       [5.482e-10, 5.025e-10, 5.386e-10]])

In [33]:
np.set_printoptions(suppress=False)
random_arr/1e10

array([[5.316e-10, 7.150e-10, 7.434e-10],
       [8.523e-10, 8.539e-10, 7.017e-10],
       [5.630e-10, 8.444e-10, 7.032e-10],
       [8.697e-10, 6.703e-10, 7.850e-10],
       [5.482e-10, 5.025e-10, 5.386e-10]])

In [34]:
np.set_printoptions(suppress=True)
random_arr/1e10

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Exercise 23. How to limit the number of items printed in output of numpy array?¶



In [35]:
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
a=np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Exercise 24. How to print the full numpy array without truncating¶



In [37]:
a=np.arange(15)
np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Exercise 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?¶



In [39]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=0,usecols=[0,1,2,3,4,5],dtype=object)
iris_data

array([[b'Id', b'SepalLengthCm', b'SepalWidthCm', b'PetalLengthCm',
        b'PetalWidthCm', b'Species'],
       [b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       ...,
       [b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']],
      dtype=object)

Exercise 26. How to extract a particular column from 1D array of tuples?¶



In [42]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=0,usecols=[-1],dtype=object)
iris_data

array([b'Species', b'Iris-setosa', b'Iris-setosa', ..., b'Iris-virginica',
       b'Iris-virginica', b'Iris-virginica'], dtype=object)

Exercise 27. How to convert a 1d array of tuples to a 2d numpy array?¶



In [45]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[0,1,2,3,4],dtype='float')
iris_data

array([[  1. ,   5.1,   3.5,   1.4,   0.2],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [  3. ,   4.7,   3.2,   1.3,   0.2],
       ...,
       [148. ,   6.5,   3. ,   5.2,   2. ],
       [149. ,   6.2,   3.4,   5.4,   2.3],
       [150. ,   5.9,   3. ,   5.1,   1.8]])

Exercise 28. How to compute the mean, median, standard deviation of a numpy array?¶



In [48]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1])
print("Mean=",np.mean(iris_data))
print("Median=",np.median(iris_data))
print("Standard deviation=",np.std(iris_data))

Mean= 5.843333333333334
Median= 5.8
Standard deviation= 0.8253012917851409


Exercise 29. How to normalize an array so the values range exactly between 0 and 1?¶



In [ ]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1])

(iris_data-np.min(iris_data))/(np.max(iris_data)-np.min(iris_data))


array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444])

Exercise 30. How to compute the softmax score?¶



In [51]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1])
softmax=np.exp(iris_data)/sum(np.exp(iris_data))
softmax.sum()

0.9999999999999997

Exercise 31. How to find the percentile scores of a numpy array?¶



In [52]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1])
np.percentile(iris_data,q=[5,95])

array([4.6  , 7.255])

Exercise 32. How to insert values at random positions in an array?¶



In [58]:
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1,2,3,4])

for i in np.random.randint(0,len(iris_data),20):
    iris_data[i]=np.nan
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [nan, nan, nan, nan]])

In [54]:
np.nan

nan

In [55]:
len(iris_data)

150

In [59]:
np.isnan(iris_data[:,:]).sum()

76

Exercise 33. How to find the position of missing values in numpy array?¶



In [2]:
import numpy as np
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1,2,3,4])

iris_data[np.random.randint(len(iris_data),size=20),np.random.randint(4,size=20)]=np.nan
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [nan, 3.2, nan, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, nan],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , nan],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
print("Number of missing values",np.isnan(iris_data[:,:]).sum())

Number of missing values 20


In [4]:
print("Position of missing values",np.where(np.isnan(iris_data[:,0])))

Position of missing values (array([  2,  48,  51,  55, 135]),)


Exercise 34. How to filter a numpy array based on two or more conditions?¶



In [5]:
import numpy as np
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1,2,3,4])
iris_data


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
iris_data[(iris_data[:,1]>1.5)&(iris_data[:,0]<5.0)]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Exercise 35. How to drop rows that contain a missing value from a numpy array?¶



In [7]:
import numpy as np
iris_data=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=1,usecols=[1,2,3,4])

iris_data[np.random.randint(len(iris_data),size=20),np.random.randint(4,size=20)]=np.nan
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, nan, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, nan, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, nan, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, nan, 1.4, 0.2],
       [4.9, 3

In [10]:
iris_data[np.sum(np.isnan(iris_data),axis=1)==0][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

In [14]:
import numpy as np
iris_data1=np.genfromtxt('data/iris.csv',delimiter=',',
                        skip_header=0,usecols=[1,2,3,4])
iris_data1

array([[nan, nan, nan, nan],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4

Exercise 36. How to find the correlation between two columns of a numpy array?¶



In [18]:
diabetes_data = np.genfromtxt('data/diabetes.csv',
                              delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7],
                                skip_header=1)

diabetes_data


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [19]:
print(np.corrcoef(diabetes_data[:,1],diabetes_data[:,2]))

[[1.         0.15258959]
 [0.15258959 1.        ]]


In [21]:
print(np.corrcoef(diabetes_data[:,1],diabetes_data[:,2])[0,1])

0.15258958656866448


Exercise 37. How to find if a given array has any null values?¶



In [22]:
diabetes_data = np.genfromtxt('data/diabetes.csv',
                              delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7], skip_header=1)
diabetes_data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [23]:
np.isnan(diabetes_data).any()

False

Exercise 38. How to replace all missing values with 0 in a numpy array?¶



In [46]:
wine_quality = np.genfromtxt('data/winequality-red.csv',
                             delimiter=',', dtype='float', usecols=[0,1,2,3,4,5,6,7,8,9,10], skip_header=1)

In [47]:
np.isnan(wine_quality).any()

False

In [52]:
wine_quality[np.random.randint(20,size=10),np.random.randint(10,size=10)]=np.nan

In [53]:
wine_quality

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,    nan,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [50]:
np.isnan(wine_quality).any()

True

In [54]:
wine_quality[np.isnan(wine_quality)]=1

In [55]:
wine_quality

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  1.   ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [56]:
np.isnan(wine_quality).any()

False

Exercise 39. How to find the count of unique values in a numpy array?¶



In [60]:
mushroom = np.genfromtxt('data/mushrooms.csv',
                             delimiter=',', dtype=object, usecols=[0,1], skip_header=1)

In [61]:
mushroom

array([[b'p', b'x'],
       [b'e', b'x'],
       [b'e', b'b'],
       ...,
       [b'e', b'f'],
       [b'p', b'k'],
       [b'e', b'x']], dtype=object)

In [62]:
np.unique(mushroom,return_counts=True)

(array([b'b', b'c', b'e', b'f', b'k', b'p', b's', b'x'], dtype=object),
 array([ 452,    4, 4208, 3152,  828, 3916,   32, 3656]))

Exercise 40. How to create a new column from existing columns of a numpy array?¶



In [63]:
iris_data = np.genfromtxt('data/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[1,2,3,4], skip_header=1)

iris_data

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2'],
       [b'4.6', b'3.1', b'1.5', b'0.2'],
       [b'5.0', b'3.6', b'1.4', b'0.2'],
       [b'5.4', b'3.9', b'1.7', b'0.4'],
       [b'4.6', b'3.4', b'1.4', b'0.3'],
       [b'5.0', b'3.4', b'1.5', b'0.2'],
       [b'4.4', b'2.9', b'1.4', b'0.2'],
       [b'4.9', b'3.1', b'1.5', b'0.1'],
       [b'5.4', b'3.7', b'1.5', b'0.2'],
       [b'4.8', b'3.4', b'1.6', b'0.2'],
       [b'4.8', b'3.0', b'1.4', b'0.1'],
       [b'4.3', b'3.0', b'1.1', b'0.1'],
       [b'5.8', b'4.0', b'1.2', b'0.2'],
       [b'5.7', b'4.4', b'1.5', b'0.4'],
       [b'5.4', b'3.9', b'1.3', b'0.4'],
       [b'5.1', b'3.5', b'1.4', b'0.3'],
       [b'5.7', b'3.8', b'1.7', b'0.3'],
       [b'5.1', b'3.8', b'1.5', b'0.3'],
       [b'5.4', b'3.4', b'1.7', b'0.2'],
       [b'5.1', b'3.7', b'1.5', b'0.4'],
       [b'4.6', b'3.6', b'1.0', b'0.2'],
       [b'5.1', b'3.3', b'1.7', b'0.5'],
       [b'4.8', 

In [65]:
sepalength=iris_data[:,0].astype('float')
petalength=iris_data[:,2].astype('float')

In [66]:
new_column=(np.pi*petalength*sepalength)
new_column

array([ 22.43097155,  21.5513256 ,  19.19513111,  21.67698931,
        21.99114858,  28.83982056,  20.23185669,  23.5619449 ,
        19.35221075,  23.090706  ,  25.44690049,  24.12743158,
        21.11150263,  14.85973325,  21.86548487,  26.86061719,
        22.05398043,  22.43097155,  30.44203281,  24.0331838 ,
        28.83982056,  24.0331838 ,  14.45132621,  27.23760831,
        28.651325  ,  25.13274123,  25.13274123,  24.5044227 ,
        22.87079452,  23.62477675,  24.12743158,  25.44690049,
        24.5044227 ,  24.19026343,  23.090706  ,  18.84955592,
        22.46238747,  23.090706  ,  17.96990998,  24.0331838 ,
        20.42035225,  18.37831702,  17.96990998,  25.13274123,
        30.44203281,  21.11150263,  25.63539605,  20.23185669,
        24.9756616 ,  21.99114858, 103.3583983 ,  90.47786842,
       106.21724762,  69.11503838,  93.93362034,  80.58185156,
        93.02255847,  50.79955321,  95.37875296,  63.71149901,
        54.97787144,  77.84866596,  75.39822369,  90.06

In [67]:
new_column=new_column[:,np.newaxis]
new_column

array([[ 22.43097155],
       [ 21.5513256 ],
       [ 19.19513111],
       [ 21.67698931],
       [ 21.99114858],
       [ 28.83982056],
       [ 20.23185669],
       [ 23.5619449 ],
       [ 19.35221075],
       [ 23.090706  ],
       [ 25.44690049],
       [ 24.12743158],
       [ 21.11150263],
       [ 14.85973325],
       [ 21.86548487],
       [ 26.86061719],
       [ 22.05398043],
       [ 22.43097155],
       [ 30.44203281],
       [ 24.0331838 ],
       [ 28.83982056],
       [ 24.0331838 ],
       [ 14.45132621],
       [ 27.23760831],
       [ 28.651325  ],
       [ 25.13274123],
       [ 25.13274123],
       [ 24.5044227 ],
       [ 22.87079452],
       [ 23.62477675],
       [ 24.12743158],
       [ 25.44690049],
       [ 24.5044227 ],
       [ 24.19026343],
       [ 23.090706  ],
       [ 18.84955592],
       [ 22.46238747],
       [ 23.090706  ],
       [ 17.96990998],
       [ 24.0331838 ],
       [ 20.42035225],
       [ 18.37831702],
       [ 17.96990998],
       [ 25

In [68]:
output=np.hstack([iris_data,new_column])

In [70]:
output[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', 22.43097154663112],
       [b'4.9', b'3.0', b'1.4', b'0.2', 21.551325603625983],
       [b'4.7', b'3.2', b'1.3', b'0.2', 19.195131113433636],
       [b'4.6', b'3.1', b'1.5', b'0.2', 21.67698930976957],
       [b'5.0', b'3.6', b'1.4', b'0.2', 21.991148575128552]], dtype=object)

Exercise 41. How to sort a 2D array by a column¶



In [71]:
diabetes_data = np.genfromtxt('data/diabetes.csv',
                              delimiter=',', dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)
diabetes_data

array([[b'6', b'148', b'72', ..., b'0.627', b'50', b'1'],
       [b'1', b'85', b'66', ..., b'0.351', b'31', b'0'],
       [b'8', b'183', b'64', ..., b'0.672', b'32', b'1'],
       ...,
       [b'5', b'121', b'72', ..., b'0.245', b'30', b'0'],
       [b'1', b'126', b'60', ..., b'0.349', b'47', b'1'],
       [b'1', b'93', b'70', ..., b'0.315', b'23', b'0']], dtype=object)

In [73]:
diabetes_data[diabetes_data[:,1].argsort()]

array([[b'1', b'0', b'74', ..., b'0.299', b'21', b'0'],
       [b'5', b'0', b'80', ..., b'0.346', b'37', b'1'],
       [b'1', b'0', b'68', ..., b'0.389', b'22', b'0'],
       ...,
       [b'4', b'99', b'72', ..., b'0.294', b'28', b'0'],
       [b'4', b'99', b'76', ..., b'0.223', b'21', b'0'],
       [b'2', b'99', b'60', ..., b'0.453', b'21', b'0']], dtype=object)

Exercise 42. How to find the most frequent value in a numpy array?¶



In [75]:
diabetes_data = np.genfromtxt('data/diabetes.csv',
                              delimiter=',', dtype=object, usecols=[0,1,2,3,4,5,6,7,8], skip_header=1)
diabetes_data


array([[b'6', b'148', b'72', ..., b'0.627', b'50', b'1'],
       [b'1', b'85', b'66', ..., b'0.351', b'31', b'0'],
       [b'8', b'183', b'64', ..., b'0.672', b'32', b'1'],
       ...,
       [b'5', b'121', b'72', ..., b'0.245', b'30', b'0'],
       [b'1', b'126', b'60', ..., b'0.349', b'47', b'1'],
       [b'1', b'93', b'70', ..., b'0.315', b'23', b'0']], dtype=object)

In [76]:
np.unique(diabetes_data[:,1],return_counts=True)

(array([b'0', b'100', b'101', b'102', b'103', b'104', b'105', b'106',
        b'107', b'108', b'109', b'110', b'111', b'112', b'113', b'114',
        b'115', b'116', b'117', b'118', b'119', b'120', b'121', b'122',
        b'123', b'124', b'125', b'126', b'127', b'128', b'129', b'130',
        b'131', b'132', b'133', b'134', b'135', b'136', b'137', b'138',
        b'139', b'140', b'141', b'142', b'143', b'144', b'145', b'146',
        b'147', b'148', b'149', b'150', b'151', b'152', b'153', b'154',
        b'155', b'156', b'157', b'158', b'159', b'160', b'161', b'162',
        b'163', b'164', b'165', b'166', b'167', b'168', b'169', b'170',
        b'171', b'172', b'173', b'174', b'175', b'176', b'177', b'178',
        b'179', b'180', b'181', b'182', b'183', b'184', b'186', b'187',
        b'188', b'189', b'190', b'191', b'193', b'194', b'195', b'196',
        b'197', b'198', b'199', b'44', b'56', b'57', b'61', b'62', b'65',
        b'67', b'68', b'71', b'72', b'73', b'74', b'75', b'76', 

In [77]:
value,count=np.unique(diabetes_data[:,1],return_counts=True)

In [78]:
value

array([b'0', b'100', b'101', b'102', b'103', b'104', b'105', b'106',
       b'107', b'108', b'109', b'110', b'111', b'112', b'113', b'114',
       b'115', b'116', b'117', b'118', b'119', b'120', b'121', b'122',
       b'123', b'124', b'125', b'126', b'127', b'128', b'129', b'130',
       b'131', b'132', b'133', b'134', b'135', b'136', b'137', b'138',
       b'139', b'140', b'141', b'142', b'143', b'144', b'145', b'146',
       b'147', b'148', b'149', b'150', b'151', b'152', b'153', b'154',
       b'155', b'156', b'157', b'158', b'159', b'160', b'161', b'162',
       b'163', b'164', b'165', b'166', b'167', b'168', b'169', b'170',
       b'171', b'172', b'173', b'174', b'175', b'176', b'177', b'178',
       b'179', b'180', b'181', b'182', b'183', b'184', b'186', b'187',
       b'188', b'189', b'190', b'191', b'193', b'194', b'195', b'196',
       b'197', b'198', b'199', b'44', b'56', b'57', b'61', b'62', b'65',
       b'67', b'68', b'71', b'72', b'73', b'74', b'75', b'76', b'77',
       

In [79]:
count

array([ 5, 17,  9, 13,  9,  6, 13, 14, 11, 13, 12,  6, 14, 13,  5, 11, 10,
        7, 11,  6, 11, 11,  6, 12,  9, 11, 14,  9,  5, 11, 14,  7,  5,  5,
        5,  6,  4,  8,  8,  5,  8,  5,  5,  5,  6,  7,  5,  9,  7,  4,  1,
        3,  6,  4,  2,  6,  5,  3,  2,  8,  2,  1,  3,  6,  3,  3,  4,  3,
        3,  4,  1,  2,  3,  1,  6,  2,  2,  2,  1,  1,  5,  5,  5,  1,  3,
        3,  1,  4,  2,  4,  1,  1,  2,  3,  2,  3,  4,  1,  1,  1,  1,  2,
        1,  1,  1,  1,  3,  4,  1,  3,  4,  2,  2,  2,  4,  3,  6,  6,  3,
        6, 10,  7,  3,  7,  9,  6, 11,  9,  9,  7,  7, 13,  8,  9,  3, 17])

In [80]:
value[np.argmax(count)]

b'100'

Exercise 43. How to find the position of the first occurrence of a value greater than a given value?¶



In [81]:
iris_data = np.genfromtxt('data/Iris.csv', delimiter=',', 
                          dtype=object, usecols=[3], skip_header=1)
iris_data

array([b'1.4', b'1.4', b'1.3', b'1.5', b'1.4', b'1.7', b'1.4', b'1.5',
       b'1.4', b'1.5', b'1.5', b'1.6', b'1.4', b'1.1', b'1.2', b'1.5',
       b'1.3', b'1.4', b'1.7', b'1.5', b'1.7', b'1.5', b'1.0', b'1.7',
       b'1.9', b'1.6', b'1.6', b'1.5', b'1.4', b'1.6', b'1.6', b'1.5',
       b'1.5', b'1.4', b'1.5', b'1.2', b'1.3', b'1.5', b'1.3', b'1.5',
       b'1.3', b'1.3', b'1.3', b'1.6', b'1.9', b'1.4', b'1.6', b'1.4',
       b'1.5', b'1.4', b'4.7', b'4.5', b'4.9', b'4.0', b'4.6', b'4.5',
       b'4.7', b'3.3', b'4.6', b'3.9', b'3.5', b'4.2', b'4.0', b'4.7',
       b'3.6', b'4.4', b'4.5', b'4.1', b'4.5', b'3.9', b'4.8', b'4.0',
       b'4.9', b'4.7', b'4.3', b'4.4', b'4.8', b'5.0', b'4.5', b'3.5',
       b'3.8', b'3.7', b'3.9', b'5.1', b'4.5', b'4.5', b'4.7', b'4.4',
       b'4.1', b'4.0', b'4.4', b'4.6', b'4.0', b'3.3', b'4.2', b'4.2',
       b'4.2', b'4.3', b'3.0', b'4.1', b'6.0', b'5.1', b'5.9', b'5.6',
       b'5.8', b'6.6', b'4.5', b'6.3', b'5.8', b'6.1', b'5.1', b'5.3',
      

In [83]:
np.argwhere(iris_data[:].astype('float')>=2.3)[0]

array([50])

Exercise 44. How to replace all values greater than a given value to a given cutoff?¶



In [86]:
np.set_printoptions(precision=2)
np.random.seed(100)
a=np.random.uniform(1,50,20)

a[a<15]=15
a[a>20]=20
a

array([20., 15., 20., 20., 15., 15., 20., 20., 15., 20., 20., 15., 15.,
       15., 15., 20., 20., 15., 20., 15.])

Exercise 45. How to convert an array of arrays into a flat 1d array?¶



In [89]:
arr1=np.arange(3)
arr2=np.arange(3,8)
arr3=np.arange(8,14)
print(arr1)
print(arr2)
print(arr3)

[0 1 2]
[3 4 5 6 7]
[ 8  9 10 11 12 13]


In [90]:
arr_combine=np.concatenate([arr1,arr2,arr3])
arr_combine

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])